apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample
spec:
  rules:
  - host: "guetbook2-dev.labs.k8s.tn"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: guestbook-ui
            port:
              number: 80